AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 Instance

Parameters:
  InstanceTypeParameter:
    Description: Select instance type Enter t2.micro, m1.small or m1.large. Default is t2.micro
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0dba2cb6798deb6d8
